x = input('Digite algo: ')
print('É um número? ', x.isnumeric())
print('É alfabético? ', x.isalpha())
print('É alfanumérico? ', x.isalnum())
print('Tem somente espaço? ', x.isspace())
print('Está somente em maiúsculo? ', x.isupper())
print('Está somente em minúsculo? ', x.islower())
print('Está capitalizado? ', x.istitle())
